#this is useless, will be removed later on, all defaults are kept in java code


# FactionsPlus Configuration File: for help with the configuration and detailed descriptions of the settings, please consult
# we cannot freaking keep comments :/ well in all honesty we could keep this header somehow

jails:
    enableJails: true
    leadersCanSetJails: true 
    officersCanSetJails: true
    membersCanSetJails: false
    leadersCanJail: true
    officersCanJail: true
warps:
    enableWarps: true
    leadersCanSetWarps: true
    officersCanSetWarps: true
    membersCanSetWarps: false
    mustBeInOwnTerritoryToCreate: true
    maxWarps: 5
    warpTeleportAllowedFromEnemyTerritory: true
    warpTeleportAllowedFromDifferentWorld: true
    warpTeleportAllowedEnemyDistance: 35
    warpTeleportIgnoreEnemiesIfInOwnTerritory: true
    smokeEffectOnWarp: true
banning:
    enableBans: true
    leadersCanFactionBan: true
    officersCanFactionBan: true
    leadersCanFactionUnban: true
    officersCanFactionUnban: true
    leaderCanNotBeBanned: true
rules:
    enableRules: true
    leadersCanSetRules: true
    officersCanSetRules: true
    maxRulesPerFaction: 12
peaceful:
    leadersCanToggleState: false
    officersCanToggleState: false
    membersCanToggleState: false
    enablePeacefulBoosts: true
    powerBoostIfPeaceful: 0
powerboosts:
    enablePowerBoosts: false
    extraPowerWhenKillPlayer: 0.0
    extraPowerLossIfDeathBySuicide: 0.0
    extraPowerLossIfDeathByPVP: 0.0
    extraPowerLossIfDeathByMob: 0.0
    extraPowerLossIfDeathByCactus: 0.0
    extraPowerLossIfDeathByTNT: 0.0
    extraPowerLossIfDeathByFire: 0.0
    extraPowerLossIfDeathByPotion: 0.0
    extraPowerLossIfDeathByOther: 0.0
announce:
    enableAnnounce: true
    leadersCanAnnounce: true
    officersCanAnnounce: true
    showLastAnnounceOnLogin: true
    showLastAnnounceOnLandEnter: true
economy:
    enableEconomy: false
    economyCostToWarp: 0
    economyCostToCreateWarp: 0
    economyCostToDeleteWarp: 0
    economyCostToAnnounce: 0
    economyCostToJail: 0
    economyCostToSetJail: 0
    economyCostToUnJail: 0
    economyCostToToggleUpPeaceful: 0
    economyCostToToggleDownPeaceful: 0
Teleports:
    # note: it is highly suggested if you use essentials teleport warmup time that you replace it with booscooldowns, the native factionsplus hook does not work if essentials teleport warmup is enabled!
    disallowTeleportingToEnemyLandViaHomeCommand: true
    # reports on console only
    reportSuccessfulByCommandTeleportsIntoEnemyLand: true
    disallowTeleportingToEnemyLandViaEnderPeals: false
    
extras:
    lwc:
        # If enabled, it is highly suggested that you change the default factions lwc integration to false.
        removeLWCLocksOnClaim: false
        blockCPublicAccessOnNonOwnFactionTerritory: false
    disguise:
        enableDisguiseIntegration: false
        unDisguiseIfInOwnTerritory: false
        unDisguiseIfInEnemyTerritory: false
    disableUpdateCheck: false
    
DoNotChangeMe: 8

